table 'All Measure'
	lineageTag: ca49749c-857a-45e0-b215-fb9cf465917f

	measure 'Total Sales' = SUM(SalesData[Sales])
		lineageTag: 4ac1cf3a-f0c7-4b86-a6d1-bb46e74a66b0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit' = SUM(SalesData[Profit])
		lineageTag: 0cfc4721-4dae-458c-b6db-b583e027e68c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Orders' = COUNT(SalesData[OrderId])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bb3552d9-ce5b-4815-a274-8af98e56ae6b

	measure 'Total Quantity Sold' = SUM(SalesData[Quantity])
		formatString: 0
		lineageTag: 88e88063-2804-40f9-8921-30f0e2cdaaac

	measure 'Parent Sales In%' = [Total Sales]/CALCULATE([Total Sales],ALLEXCEPT(Products,Products[Category]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a0643c80-87ff-47b4-acb9-2d8a64cdeba1

	measure 'Ship Date Sales' = CALCULATE([Total Sales],USERELATIONSHIP(SalesData[ShipDateKey],DateTable[DateKey]))
		lineageTag: 9c5b3809-4d04-4440-92b4-73c6828bab44

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'All Measure' = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				  #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

